# File field settings
field.widget.third_party.fiu:
  type: mapping
  label: 'Fiu field widget settings'
  mapping:
    fiu_show_file_name:
      type: string
      label: 'Fiu show/hide file name/path'
